In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('Sample').getOrCreate()

In [12]:
rdd = spark.sparkContext.parallelize(range(1000))

# to generate random numbers 
rdd.sample(False,0.1,10).collect()

[5,
 19,
 20,
 29,
 35,
 47,
 66,
 70,
 81,
 93,
 94,
 96,
 97,
 126,
 138,
 141,
 160,
 162,
 163,
 188,
 191,
 199,
 210,
 219,
 221,
 231,
 261,
 262,
 271,
 272,
 277,
 281,
 286,
 287,
 291,
 300,
 305,
 317,
 322,
 327,
 330,
 334,
 337,
 356,
 357,
 373,
 377,
 380,
 384,
 396,
 398,
 399,
 402,
 405,
 411,
 413,
 416,
 418,
 421,
 422,
 423,
 436,
 437,
 466,
 467,
 501,
 515,
 520,
 522,
 529,
 559,
 568,
 580,
 581,
 583,
 602,
 622,
 627,
 628,
 631,
 649,
 654,
 683,
 709,
 713,
 715,
 718,
 726,
 729,
 733,
 735,
 740,
 749,
 752,
 771,
 779,
 782,
 791,
 792,
 794,
 795,
 801,
 806,
 818,
 823,
 831,
 838,
 842,
 860,
 866,
 867,
 876,
 879,
 890,
 891,
 895,
 898,
 908,
 915,
 926,
 935,
 940,
 944,
 948,
 952,
 980,
 983,
 988,
 999]

In [18]:
dict = {'a':0.01,'b':0.04}
rdd2 = spark.sparkContext.parallelize(dict.keys()).cartesian(spark.sparkContext.parallelize(range(0,1000)))
rdd2.sampleByKey(False,dict).collect()

[('a', 138),
 ('a', 164),
 ('a', 187),
 ('a', 217),
 ('a', 407),
 ('a', 524),
 ('a', 572),
 ('a', 758),
 ('b', 54),
 ('b', 101),
 ('b', 103),
 ('b', 134),
 ('b', 135),
 ('b', 142),
 ('b', 150),
 ('b', 166),
 ('b', 172),
 ('b', 192),
 ('b', 255),
 ('b', 276),
 ('b', 289),
 ('b', 315),
 ('b', 320),
 ('b', 381),
 ('b', 456),
 ('b', 485),
 ('b', 491),
 ('b', 498),
 ('b', 520),
 ('b', 609),
 ('b', 625),
 ('b', 659),
 ('b', 667),
 ('b', 688),
 ('b', 728),
 ('b', 733),
 ('b', 744),
 ('b', 755),
 ('b', 773),
 ('b', 799),
 ('b', 863),
 ('b', 926),
 ('b', 965)]